name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazel: ["4.2.1"]
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: ${{ matrix.bazel }}
      - name: test
        working-directory: test
        run: bazel test //...
